# Simple workflow for deploying static content to GitHub Pages
name: Deploy site content to Apache

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy to Apache Server
        run: rsync -r --delete-after $GITHUB_WORKSPACE/ /var/www/miamibeachcocktails.com/html/
         # O reinicia Apache (dependiendo de tus necesidades)
         # systemctl restart apache2
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

         
